# Generated by Django 4.1.7 on 2023-03-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="name",
            field=models.CharField(default=1, max_length=255, verbose_name="Name"),
            preserve_default=False,
        ),
    ]
