# Generated by Django 4.1.7 on 2023-04-03 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0002_status_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "db_table": "statuses_customstatus",
            },
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
