# Generated by Django 4.1.7 on 2023-04-03 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0003_customstatus_delete_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomStatus",
            new_name="Status",
        ),
        migrations.AlterModelTable(
            name="status",
            table=None,
        ),
    ]
