# Generated by Django 4.1.7 on 2023-04-13 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"verbose_name": "Label", "verbose_name_plural": "Метки"},
        ),
    ]
